from constants import (ALLSVENSKAN_ID, ALLSVENSKAN_SEASON2018_ID, MLS_ID, MLS_SEASON2018_ID,
                        BRSERIEA_ID, BRSERIEA_SEASON2018_ID, BRSERIEB_ID, BRSERIEB_SEASON2018_ID,
                        PREMIER_LEAGUE_ENGLAND_ID, PREMIER_LEAGUE_ENGLAND_SEASON2018_ID)
from tournaments.base import BaseTournament


class Allsvenskan(BaseTournament):
    TOURNAMENT_ID = ALLSVENSKAN_ID
    TOURNAMENT_SEASON_ID = ALLSVENSKAN_SEASON2018_ID
    BY_ROUND = True


class MLS(BaseTournament):
    TOURNAMENT_ID = MLS_ID
    TOURNAMENT_SEASON_ID = MLS_SEASON2018_ID
    BY_MATCH = True


class BRSerieA(BaseTournament):
    TOURNAMENT_ID = BRSERIEA_ID
    TOURNAMENT_SEASON_ID = BRSERIEA_SEASON2018_ID
    BY_ROUND = True


class BRSerieB(BaseTournament):
    TOURNAMENT_ID = BRSERIEB_ID
    TOURNAMENT_SEASON_ID = BRSERIEB_SEASON2018_ID
    BY_ROUND = True


class PremierLeagueEngland(BaseTournament):
    TOURNAMENT_ID = PREMIER_LEAGUE_ENGLAND_ID
    TOURNAMENT_SEASON_ID = PREMIER_LEAGUE_ENGLAND_SEASON2018_ID
    BY_ROUND = True
